version: '3'
services:
  main:
    build: ./services/main/docker-dev
    volumes:
      - ./services/main/src:/app/src
      - ./data:/app/data
    env_file:
      - ./.env
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  data-pipeline:
    build: ./services/data-pipeline/docker-dev
    volumes:
      - ./services/data-pipeline/src:/app/src
      - ./data:/app/data
    tty: true

  opencv-distorition:
    build: ./services/opencv-distorition/docker-dev
    volumes:
      - ./services/opencv-distorition/src:/app/src
      - ./data:/app/data
    tty: true

  yolo-localization:
    build: ./services/yolo-localization/docker-dev
    volumes:
      - ./services/yolo-localization/src:/app/src
      - ./data:/app/data
    entrypoint: ["python", "./src/app.py"]
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - gpu

  clip-classifier:
    build: ./services/clip-classifier/docker-dev
    volumes:
      - ./services/clip-classifier/src:/app/src
      - ./data:/app/data
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - gpu