version: '3'
services:
  yolo:
    build: ./yolo/docker-dev
    volumes:
      - ./yolo/src:/app/src
    tty: true
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - gpu
  data-pipeline:
    build: ./data-pipeline/docker-dev
    volumes:
      - ./data-pipeline/src:/app/src
      - ./data:/app/data
    tty: true
    ports:
      - "5001:5001"
