version: '3'
services:
  main:
    build: ./services/main/docker-dev
    volumes:
      - ./services/main/src:/app/src
      - ./data:/app/data
    entrypoint: ["python", "./src/app.py"]
    env_file:
      - ./.env
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5050:5000"

  opencv-distortion:
    build: ./services/opencv-distortion/docker-dev
    volumes:
      - ./services/opencv-distortion/src:/app/src
      - ./data:/app/data
    entrypoint: ["python", "./src/app.py"]
    tty: true

  distance-calculation:
    build: ./services/distance-calculation/docker-dev
    volumes:
      - ./services/distance-calculation/src:/app/src
      - ./data:/app/data
    entrypoint: ["python", "./src/app.py"]
    tty: true

  yolo-localization:
    build: ./services/yolo-localization/docker-dev
    volumes:
      - ./services/yolo-localization/src:/app/src
      - ./data:/app/data
    entrypoint: ["python", "./src/app.py"]
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - gpu

  clip-classifier:
    build: ./services/clip-classifier/docker-dev
    volumes:
      - ./services/clip-classifier/src:/app/src
      - ./data:/app/data
    entrypoint: ["python", "./src/app.py"]
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - gpu